# Base Image
FROM python:3.12-slim

# Arbeitsverzeichnis
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Projekt kopieren
COPY src/ ./src/
COPY templates/ ./templates/
COPY static/ ./static/

# Expose Flask Port
EXPOSE 5000

# Start
CMD ["python", "src/app.py"]
