# Base Image
FROM python:3.12-slim

WORKDIR /app

# SQLite installieren + Abhängigkeiten
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev && rm -rf /var/lib/apt/lists/*

# Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Applikation + DB kopieren
COPY app/ ./app/

EXPOSE 5000

CMD ["python", "app/app.py"]
