# Base Image
FROM python:3.12-slim

# Arbeitsverzeichnis im Container
WORKDIR /app

# Abhängigkeiten installieren
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Applikation kopieren
COPY app/ ./app/

# Flask Port
EXPOSE 5000

# Startbefehl
CMD ["python", "app/app.py"]
